### ISSUE TITLE
Configuration for Nextcloud Groups, does not persist

### ISSUE THREAD

**Issue by GauthierCrp** [LibreSign/libresign#3231] opened 2024-06-26 15:22 UTC
Hello !

On Nextcloud 29.0.3, I'm facing an issue in the configuration page, for groups which can request for signing documents.
 I've created a specific group called "Libresign" and put users who can ask for signing inside.

In the configuration in Nextcloud, I can choose the group, then a pop-up ask me for the admin password, and everything seems to be ok. 
But If I refresh the page, the groupe choosed desappear. The field stay blank.
If I choose again the "Libresign" group, no password is asked. But at every refresh, the group desappear.

In fact, the parameter seems to be applied by Nextcloud, but with this display bug, it is not easy to configure multiple groups in the future.

![image](https://github.com/LibreSign/libresign/assets/30144651/d4b07378-7a57-4790-81ad-2bebe27786fa)

![image](https://github.com/LibreSign/libresign/assets/30144651/74eaf797-f927-4ccb-be69-cdccf310cb6d)

![image](https://github.com/LibreSign/libresign/assets/30144651/dd2ac0e6-dfd5-4118-81e4-1cc167927943)

Could you please check it ?

Many Thanks,

Best Regards
Gauthier.

**Comment by vitormattos** [comment] 2024-06-26 15:58
What's the LibreSign version?

**Comment by GauthierCrp** [comment] 2024-06-26 16:31
![image](https://github.com/LibreSign/libresign/assets/30144651/55463363-8826-47c7-8a63-7f0e42df7817)
9.1.0

**Comment by GauthierCrp** [comment] 2024-06-28 05:47
9.1.1 for now :)

**Comment by vitormattos** [comment] 2024-07-10 00:33
Hi @GauthierCrp I can't reproduce this. Could you check if follow with this problem using latest version of Nextcloud server 29 and latest version of LibreSign?

**Comment by vitormattos** [comment] 2024-11-15 19:46
Could you check again at the newest release of LibreSign?

Closing this issue as solved after newest release. I can't reproduce this.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Closed by vitormattos** 2024-11-15 19:46 UTC
