### ISSUE TITLE
Failure on download cfssl try again

### ISSUE THREAD

**Issue by panchtatvam** [LibreSign/libresign#1792] opened 2023-07-21 06:49 UTC
**Describe the bug**
404 error on trying to install CFSSL using `occ`

**To Reproduce**
- Reached `CFSSL not installed.` step and tried installing CFSSL using `sudo -u www-data ./occ libresign:install --cfssl`
- I get 404 error `failure on download cfssl try again.
Client error: "GET http://mirror.archlinuxarm.org/aarch64/community/cfssl-1.6.3-1-aarch64.pkg.tar.xz" resulted in a "404 Not Found" response`

**Expected behavior**
CFSSL should be downloaded

**Screenshots**

- Installed till CFSSL

---------

![Screenshot 2023-07-21 at 12-13-34 LibreSign - Administration settings - Vyomnet Cloud](https://github.com/LibreSign/libresign/assets/1580970/afc9c6a0-5140-4292-a691-69827b060d66)

- Download error

-------------

![image](https://github.com/LibreSign/libresign/assets/1580970/e4703dbb-6d52-40b8-85e9-adc46bf3e5d6)

**Environment information (please complete the following information):**
 - OS: Debian 11 on ARM64
 - LibreSign Version 7.1.1
 - Nextcloud Server Version 26.0.2

**Additional context**
- Using ARM64 processor

**Comment by enrauk** [comment] 2023-11-17 11:29
I am also getting the same error; is there a way to manually install to get around this problem?

**Comment by vitormattos** [comment] 2023-11-17 15:24
I think that the problem is about the processor architecture.

And yes, you can download the cfssl binary and do handmade the configuration.

You will need to download the cfssl here:

https://github.com/cloudflare/cfssl/releases

And do the configuration of this appsetting with the path of binary:

https://github.com/LibreSign/libresign/blob/main/lib/Handler/CertificateEngine/CfsslHandler.php#L200C63-L200C72

If you prefer fix the downloaded file to Arm processor, will be necessary fix here:

https://github.com/LibreSign/libresign/blob/main/lib/Service/InstallService.php#L501-L504

I will maintain this issue open because will be necessary change the code and increase the compatibility with ARM.

If you wish to help keeping live the development of this project, you can help by sponsor: https://github.com/sponsors/LibreSign or contacting us to receive business support: contact@librecode.coop

**Comment by vitormattos** [comment] 2024-06-25 02:52
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Closed by vitormattos** 2024-06-25 02:52 UTC
