### ISSUE TITLE
After signing, a .pdf.p7s file appears instead of .signed.pdf file

### ISSUE THREAD

**Issue by DazeEnd** [LibreSign/libresign#3788] opened 2024-10-10 21:04 UTC
**Describe the bug**
When signing a document using "click to sign", sometimes a `filename.pdf.p7s` file can be left behind. When this happens, the expected `filename.signed.pdf` file is never created. As a result, the signed version of the document cannot be opened or viewed (because it doesn't exist). When downloaded, the `filename.pdf.p7s` file is zero bytes (0 B).

**To Reproduce**
I cannot reproduce the issue, however my customer has encountered it twice. These are the steps he is following, as best as I can tell:

1. Log into Nextcloud as a user (which we will call "REQUESTING-USER").
2. Upload a document (which we will call "filename.pdf"), and request a signature from another user (which we will call "SIGNING-USER"). My customer was sending the signature request to a guest account created with the Guests app (https://apps.nextcloud.com/apps/guests), but I'm not sure if that is required to reproduce the issue.
3. Log out of Nextcloud.
4. Log into Nextcloud into any Nextcloud account that is not REQUESTING-USER or SIGNING-USER. We will call this account "THIRD-USER".
5. As THIRD-USER, open the signing link that was emailed to the signer. This will display a 404 error ("Invalid user"). (See screenshot 1, below.)
6. Log out of Nextcloud.
7. Open the signing link that was emailed to the signer. This should take you to a Nextcloud login screen.
8. Log into Nextcloud as SIGNING-USER.
9. Create a signature, if necessary, and sign the document.

**Expected behavior**
1. After signing the document, the confetti screen should be displayed.
2. When viewing the list of files in LibreSign, the signed file should appear in the "signed" state, and the icon used should be a PDF icon.
3. When validating the signature in LibreSign, clicking the "View" button should display the signed version of the file, with the signature displayed.
4. In the Files app, when viewing the directory that contained the original file, there should be both the original `filename.pdf` file, and a new `filename.signed.pdf` file that contains the signed document.

**Actual behavior**
1. After signing the document, the confetti screen is properly displayed.
2. When viewing the list of files in LibreSign, the signed file properly appears in the "signed" state, but the icon is just a plain gray icon. (See Screenshot 2, below.)
3. When validating the signature in LibreSign, clicking the "View" button downloads a file called `filename.p7s` instead of displaying the signed document. The `filename.p7s` file is zero bytes (0 B), and completely empty.
4. In the Files app, when viewing the directory that contained the original file, the original `filename.pdf` file is still present, but there is no `file.signed.pdf` file. Instead, `filename.pdf.p7s` file is present. The `filename.pdf.p7s` file is completely empty (zero bytes). (See Screenshot 3, below.)

**Screenshots**
1. 404 Error screen displayed after step 5.
![Screenshot from 2024-10-10 15-44-37](https://github.com/user-attachments/assets/af4d0e79-6a52-405a-a819-40de04cc008b)

2. Corrupted (?) signed files displayed with a gray icon:
![Screenshot from 2024-10-10 16-33-48](https://github.com/user-attachments/assets/d102a458-2ada-491a-bcf3-e0a7df58a291)

3. The `adam.PDF.p7s` file was created as a result of signing `adam.PDF`. The `adam.PDF.p7s` file is completely empty.
![Screenshot from 2024-10-10 15-37-19](https://github.com/user-attachments/assets/19126992-f2f1-4f31-89b3-9a7f2a3f4c99)

4. Screen 1 of LibreSign settings.
![Screenshot from 2024-10-10 16-45-25](https://github.com/user-attachments/assets/644ac715-9c3d-4af8-9693-706190735876)

5. Screen 2 of LibreSign settings.
![Screenshot from 2024-10-10 16-46-09](https://github.com/user-attachments/assets/9b15fa3b-5ff1-4744-a14b-20073de09d8d)

6. Screen 3 of LibreSign settings.
![Screenshot from 2024-10-10 16-46-40](https://github.com/user-attachments/assets/5b2c7ccb-9b6b-4ef3-a33e-79cf9235fc7b)

**Environment information (please complete the following information):**
 - Server OS: AlmaLinux 8.4
 - Browser: Chrome (unknown version)
 - LibreSign Version: v8.2.4
 - Nextcloud Server Version: 28.0.8
 - Logs (generated with `cat nextcloud.log | grep -i libresign | grep "2024-10-10"`): [nextcloud.log](https://github.com/user-attachments/files/17334175/nextcloud.log)

**Additional context**
My customer is experiencing this as he is testing out LibreSign, and trying to learn how it works. Essentially, he is sending signature requests to himself or a co-worker as a test. The problem seems to be appearing, because the recipient is already logged into another account when they click on the link in the email they receive. From my customer's experience, LibreSign is repeatedly failing during his tests, and this is causing the customer to mistrust the tool and become reluctant to rely on it for production use (even though this combination of events is unlikely to happen in a real-life scenario).

**Comment by DazeEnd** [comment] 2024-10-11 12:25
Just to be clear, I agree that what the user doing is extremely unusual. Especially the part where a third user is accessing the signing link. I also agree that this scenario is very unlikely to come up in actual use.

I don't know where the p7s file is coming from either. The customer says he is not uploading the p7s file, and that it is appearing after he signs the original PDF.

I cannot reproduce the issue. The customer cannot reliably reproduce the issue, but it happened to him three times yesterday. I am going to try to schedule a video call with him today so that I can watch what exactly he is doing. If I am able to collect more information, I will share it.

So I guess my main question right now is where is this p7s file coming from? Are you saying that LibreSign isn't creating it?

**Comment by vitormattos** [comment] 2024-10-11 12:41
> I am going to try to schedule a video call with him today so that I can watch what exactly he is doing. If I am able to collect more information, I will share it.

See if you can record the call; it would be good because if you can see the problem, we have a video that can give some light.

> So I guess my main question right now is where is this p7s file coming from? Are you saying that LibreSign isn't creating it?

Is this, the only point at the code that could generate a p7s is this:

https://github.com/LibreSign/libresign/blob/3863a4f9aae56eccf7214af1b643890ca3292769/lib/Service/SignFileService.php#L265-L283

There is no way today in the frontend to request that a file that is not a PDF be signed, so I don't see how a p7s could have been created. Is it possible that this client of yours is using the Nexcloud Desktop Client and is signing the document with some other software and generating the p7s file?

**Comment by DazeEnd** [comment] 2024-10-11 12:52
>  Is it possible that this client of yours is using the Nexcloud Desktop Client and is signing the document with some other software and generating the p7s file?
No, I am certain that he is not using the desktop client. I have blocked the desktop client for this Nextcloud installation by blocking its user agent.

**Comment by vitormattos** [comment] 2024-10-21 15:21
I saw now the video. I identified that the file extensions at this tests is uppercase (PDF), I don't know if this could affect but I will check.

**Comment by vitormattos** [comment] 2024-10-21 16:25
The problem is the extension in uppercase.
I will fix this at next release.

**Comment by DazeEnd** [comment] 2024-10-21 17:15
Fantastic. Thanks.

**Comment by vitormattos** [comment] 2024-10-23 11:54
Closing as solved.

This fix will come in the next release.

You can follow helping us making tests at the next release and giving your feedback about our work here.

**Closed by vitormattos** 2024-10-23 11:54 UTC
