### ISSUE TITLE
Invalid password

### ISSUE THREAD

**Issue by tasagore** [LibreSign/libresign#2505] opened 2024-03-08 21:30 UTC
Hi

I've upgraded from RC5 to RC7 and still every time I try to sign a file I get the invalid password error and it's right. Tested in two instances (same server).

I thought this was fixed, isn't it?

Regards

**Comment by JeffStarkman** [comment] 2024-03-08 21:57
First, thanks for the good work!

Nextcloud 28.0.3, PHP 8.2. LibreSign rc6 / rc7
I have the same problem. I created a certificate with: user - libresign - settings - create certificate. After creation, I change the password 2 times to see if I use the correct password. this works.

Now try to sign a pdf, i get always the message "wrong password".

Second try, I import a certificate file "mycert.pfx" with a known password, I get the same error.

Greetings

**Comment by JeffStarkman** [comment] 2024-03-08 23:12
Additional Information, I found this error in my nextcloud Log:

[PHP] Fehler: Undefined array key "profileElementId" at /var/www/nextcloud/apps/libresign/lib/Helper/ValidateHelper.php#306
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/e9e23453-ff3c-4fe3-9373-3c77a5bf51bd

**Comment by vitormattos** [comment] 2024-03-12 15:13
@JeffStarkman could you provide the scenario to reproduce this problem? Looking at the code, this isn't related with password and I can't create a scenario to reproduce your report.

**Comment by JeffStarkman** [comment] 2024-03-12 21:55
- Create a certifikate with known password:

![grafik](https://github.com/LibreSign/libresign/assets/162755819/ff519288-814e-4b07-a75d-15edc87efb15)
- ok
- change password:
![grafik](https://github.com/LibreSign/libresign/assets/162755819/b2a7f965-0d5f-49d0-b848-0581fc278a46)

- Password change is ok
- sign a document:

![grafik](https://github.com/LibreSign/libresign/assets/162755819/2689b995-8e64-45e5-95c5-a3d7d1895684)

![grafik](https://github.com/LibreSign/libresign/assets/162755819/67042149-fa9f-45f2-bf6e-546ee252ffde)


Error in the right upper corner:

![grafik](https://github.com/LibreSign/libresign/assets/162755819/b7dc8ec6-4c95-42a6-996d-c7fa6d579eaf)

- same in the way, click on Icon:
![grafik](https://github.com/LibreSign/libresign/assets/162755819/785c07c9-3b15-4bde-b74b-7409dd97d8d4)

- signing windows as a overlay, same result

![grafik](https://github.com/LibreSign/libresign/assets/162755819/ac788434-1a5d-4f8e-b735-780d4ff62dc8)


- error Log:

  [PHP] Fehler: Undefined array key "profileElementId" at /var/www/nextcloud/apps/libresign/lib/Helper/ValidateHelper.php#306
  POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/2bd4563b-9932-4c91-a19b-c33b48b994ee
  
- my System:

  Betriebssystem: **Linux 5.15.0-100-generic x86_64**

  Prozessor:	**Intel(R) N100 (2 cores)**

  Speicher:	 **9\.67 GB**

  Server-Zeit: **Tue Mar 12 22:39:07 CET 2024** 

- PHP 

  Version:			*8\.2.16*
  Speicherlimit:		*4 GB*
  Maximale Ausführungszeit:	*3600*

  Maximale Größe zum Hochladen:	*8 GB*
  OPcache-Revalidierungshäufigkeit:	*2*

  Erweiterungen:	*Core, date, libxml,  openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL,  session, standard, sodium, cgi-fcgi, pdlib, PDO, xml, apcu, bcmath, bz2,  calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext,  gmp, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack,  pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML,  smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader,  xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache*

- Database

  Art:	*pgsql*
  Version:	*PostgreSQL 14.11 (Ubuntu  14.11-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu  11.4.0-1ubuntu1\~22.04) 11.4.0, 64-bit*
  Größe:		*643,7 MB*

**Comment by tasagore** [comment] 2024-03-15 15:56
> @JeffStarkman could you provide the scenario to reproduce this problem? Looking at the code, this isn't related with password and I can't create a scenario to reproduce your report.

Hi, since you can't create a scenario to reproduce it and a few of us have the same problem I can setup a VM with all stuff installed and give you access or send you a link to download the entire VM and make your own test locally if it helps.

**Comment by vitormattos** [comment] 2024-03-16 13:27
Hi @tasagore I'm making improvements at flow to generate root certificate and also to generate the signer certificate here:
https://github.com/LibreSign/libresign/pull/2524

It might be a good idea to wait for these improvements to be completed as I won't be able to test in another environment at the moment.

If the problem persists on your side after this pull request, I will be very happy to be able to reproduce the steps in an environment where the problem is occurring.

We are currently in need of financing for the project to be able to pay for the development as today the project does not have the funds to maintain itself financially.

**Comment by vitormattos** [comment] 2024-03-16 23:22
@tasagore and @JeffStarkman 
I published now the RC-8 with a lot of improvements at certificates. Could test again?
I recommend to generate a new root cert because I made changes at root cert generation too.

**Comment by JeffStarkman** [comment] 2024-03-19 20:25
I have tested again (rc8), with the following steps:
- delete root certificate
- create new root certifikate
- upload a pdf 
![grafik](https://github.com/LibreSign/libresign/assets/162755819/0f898dd1-027f-49ab-b2dc-d67b90cdeb43)
- sign 
![grafik](https://github.com/LibreSign/libresign/assets/162755819/678880c6-a809-4a2b-bd89-534c4662db74)
- insert password
![grafik](https://github.com/LibreSign/libresign/assets/162755819/93f09e90-fca6-4c24-ae71-7da9102c2f9e)

=> same error

back to settings, I take a look at my certificate and also try to change my password:

- read my certificate
![grafik](https://github.com/LibreSign/libresign/assets/162755819/3316380d-bed0-45ae-b3a2-85309af17157)

=> ok

- change password (from 123456 to 1234 and vice versa)
![grafik](https://github.com/LibreSign/libresign/assets/162755819/9eb97489-574c-4b1c-95de-fbb6f11e0df1)

=> ok
- read my certificate with new password

=> ok

my settings with openssl:
![grafik](https://github.com/LibreSign/libresign/assets/162755819/3d67dd9a-2c58-4dce-a2e0-ed5281e9357e)

warnings in log:
[PHP] Fehler: Undefined array key "OU" at /var/www/nextcloud/apps/libresign/lib/Handler/CertificateEngine/AEngineHandler.php#138
	POST /ocs/v2.php/apps/libresign/api/v1/account/pfx/read

i didnt fillout the field "OU", so maybe this error is not important

nextsteps for me, 
- I will delete the root certificate, my certificate, 
- change to CFSSL
- create a new root-ca (with all fields) and a new personell certificate
- and test again:
![grafik](https://github.com/LibreSign/libresign/assets/162755819/1e74e73f-60ee-4853-8679-9fc04c3fe1a2)

=> same error

next try, make updates (most php8.2), uninstall libresign, reboot and install libresign again:
- make a new personell certificate

=> same error

I found a new error in log:
[PHP] Fehler: fsockopen(): Unable to connect to 127.0.0.1:8888 (Connection refused) at /var/www/nextcloud/apps/libresign/lib/Handler/CertificateEngine/CfsslHandler.php#269
	GET /apps/files

short story:
in settings and personel settings I can change / create certificate and passwords, every thing works.

Remark: if I read my certificate and type a wrong password, I get no msg Password wrong, I have to close the small window
![grafik](https://github.com/LibreSign/libresign/assets/162755819/8749b0d3-ff9a-441b-9e23-2178565bd7d1)
(the circle dont stop rotating)

an type it again.

only in the last step signing the document, it won't work.

helpfull was the new "read certificate" button to check the password!


Greetings

**Comment by tasagore** [comment] 2024-03-20 18:03
@vitormattos same with RC8, invalid password. I've deleted the root cert, the personal cert, change passwords...no way, always same error.

**Comment by vitormattos** [comment] 2024-03-22 01:37
Hi @tasagore could you provide the entire row log of this entry? The backtrace could help to identify what happening.

**Comment by tasagore** [comment] 2024-03-23 09:15
Entire row log? Do you mean the nextcloud.log content?

**Comment by vitormattos** [comment] 2024-03-24 18:02
No, only the rows of the errors that stays in your print screen.

**Comment by vitormattos** [comment] 2024-03-26 17:49
Maybe was resolved by: #2599
Wait next release candidate

**Comment by vitormattos** [comment] 2024-03-27 17:19
> [PHP] Fehler: Undefined array key "profileElementId" at /var/www/nextcloud/apps/libresign/lib/Helper/ValidateHelper.php#306
> POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/e9e23453-ff3c-4fe3-9373-3c77a5bf51bd

Fixed by:
- #2605

**Comment by vitormattos** [comment] 2024-03-28 02:39
Fixed at https://github.com/LibreSign/libresign/releases/download/v8.0.0-rc9/libresign-v8.0.0-rc9.tar.gz

**Closed by vitormattos** 2024-03-28 02:39 UTC

**Comment by JeffStarkman** [comment] 2024-03-28 18:51
works also for me after installed version rc9:

- update LibresignApp to version rc9
- sign an "old" pdf (see last tries above, _very_ old PDF)

after insert password a get an error in the upper right corner:
````
The chosen hash algorithm (SHA-1) requires a newer PDF version (PDF-1.3) than the original (PDF-1.2).
THe PDF version update is impossible in the "append" signature mode.
Either disable the append mode or pick another hash algorithm.
These are the algorithm requirements: SHA-1 (PDF-1.3, SHA-256 (PDF-1.6), SHA-384 (PDF-1.7), SHA-512 (PDF-1.7), RIPEMD160 (PDF-1.7)
````
- create and sign a new PDF (PDF version 1.5)

=> **IT WORKS!**

**Comment by vitormattos** [comment] 2024-03-28 21:02
Hi @JeffStarkman this is an error message from JSignPdf that haven't support to PDF-1.2
