### ISSUE TITLE
missing Symfony TableCellStyle for occ libresign:configure:check

### ISSUE THREAD

**Issue by unnilennium** [LibreSign/libresign#1280] opened 2022-12-16 05:56 UTC
**Describe the bug**

**To Reproduce**
-log to your server using ssh
- run occ command
- see error
```
# occ libresign:configure:check
PRÉCIS Default property file doesn't exists.
PRÉCIS Default property file doesn't exists.
An unhandled exception has been thrown:
Error: Class 'Symfony\Component\Console\Helper\TableCellStyle' not found in /usr/share/nextcloud/apps/libresign/lib/Command/Configure/Check.php:71
Stack trace:
#0 /usr/share/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Libresign\Command\Configure\Check->execute()
#1 /usr/share/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#2 /usr/share/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#3 /usr/share/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /usr/share/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /usr/share/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#6 /usr/share/nextcloud/console.php(100): OC\Console\Application->run()
#7 /usr/share/nextcloud/occ(11): require_once('/usr/share/next...')
#8 {main}

```

**Expected behavior**
running the check with expected output

**Environment information (please complete the following information):**
 - OS: Centos7
 - LibreSign Version 5.2.1
 - Nextcloud Server Version 24.0.8
 
**Additional context**
```
# ls /usr/share/nextcloud/3rdparty/symfony/console/Helper/Table*
/usr/share/nextcloud/3rdparty/symfony/console/Helper/TableCell.php  
/usr/share/nextcloud/3rdparty/symfony/console/Helper/TableRows.php       
/usr/share/nextcloud/3rdparty/symfony/console/Helper/TableStyle.php
/usr/share/nextcloud/3rdparty/symfony/console/Helper/Table.php     
 /usr/share/nextcloud/3rdparty/symfony/console/Helper/TableSeparator.php

# find /usr/share/nextcloud/ -iname TableCell*
/usr/share/nextcloud/3rdparty/symfony/console/Helper/TableCell.php

```

**Comment by vitormattos** [comment] 2022-12-17 15:41
This problem don't affect the working of LibreSign, this is a problem when show the result of tests because we got a dependency conflict, in integration tests isn't possible to reproduce this error, but we identified and was fixed on version compatible with Nextcloud 25.

Because we haven't a customer or person or anything entity funding this project, isn't possible increase our work maintaining compatible with Nextcloud 24, for now we stopped to do support and update the version compatible with Nextcloud 24. If you want to have your LibreSign up to date, will be necessary migrate to Nextcloud 25.

**Closed by vitormattos** 2022-12-17 15:41 UTC

**Comment by Githopp192** [comment] 2023-02-25 21:25
can confirm - same error: 

occ libresign:configure:check
FINE Default property file doesn't exists.
FINE Default property file doesn't exists.
An unhandled exception has been thrown:
Error: Class 'Symfony\Component\Console\Helper\TableCellStyle' not found in /var/www/html/nextcloud/apps/libresign/lib/Command/Configure/Check.php:71
Stack trace:
#0 /var/www/html/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Libresign\Command\Configure\Check->execute()
#1 /var/www/html/nextcloud/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#2 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#3 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/html/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#5 /var/www/html/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#6 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#7 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
