### ISSUE TITLE
Allow inserting of additional fields when signing

### ISSUE THREAD

**Issue by bigbeka** [LibreSign/libresign#2888] opened 2024-04-24 18:00 UTC
When creating a signer as an author, I want to be able to enable insertion of Name and Signature Date&Time next to the signature, so that that information appears on the document when signer signs the document.

See suggested addition in red in addition to the signers signature:

<img width="771" alt="Screenshot 2024-04-24 at 19 59 23" src="https://github.com/LibreSign/libresign/assets/53529055/72746483-e7ba-4161-a8d6-d3b6eddb52d4">

**Comment by vitormattos** [comment] 2024-04-24 18:12
Duplicate of #1766

**Closed by vitormattos** 2024-04-24 18:12 UTC
Labels: feature-request
