### ISSUE TITLE
possible large file not able to sign

### ISSUE THREAD

**Issue by manuelkamp** [LibreSign/libresign#1917] opened 2023-10-29 17:07 UTC
**Describe the bug**
Error whle signing a pdf with 120 pages.

**To Reproduce**
sign as usual a large pdf, error occurs.

**Expected behavior**
being able to sign also large files.

**Screenshots**
na

**Environment information (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser edge
 - LibreSign Version 7.1.1
 - Nextcloud Server Version 27.1.3
 - Logs Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) at /var/www/nextcloud/apps/libresign/vendor/libresign/tcpdi_parser/src/tcpdi_parser.php#891

**Comment by vitormattos** [comment] 2023-10-29 18:45
What's the size of this PDF to be possible reproduce?
For now, at current version of LibreSign, the project JSignPdf is used to sign a document, if is possible, would you do a test locally using JSignPDF to check if is possible to sign your large file?

**Comment by vitormattos** [comment] 2023-10-29 18:46
Spoiler: Only a random comment, probability, in the next version of LibreSign, will be possible change the sign engine at admin area between JSignPDF or this package: https://github.com/jeidison/pdf-signer-php

**Comment by manuelkamp** [comment] 2023-10-29 18:57
in file size it is 3,5mb, it has 138 pages, a lot of references, links, images etc. (it is one of my bachelor thesis i wrote in ms word-i think it was ms word 2013 back then - and safed there as pdf). I also found another documents (single pagers) which fails with "Impossible get metadata from this file." from that same time era - maybe it is a legacy issue in pdf somehow...
but yes, I am willing to test it further, if you consider it helpful.

random reaction :) I prefer to not have a docker container, since I am running another container solution (LXC) and I see no sense in having docker inside of lxcs. but just a personal opinion. It is sometimes hard to install docker solutions bare metal in lxc ;)

**Comment by vitormattos** [comment] 2023-10-29 19:06
Dockrer isn't a requirement to use LibreSign. If you prefer, ou can use LXC.

I will like if you would do a test using JSignPDF.

About metadata, this is in another part of LibreSign and maybe this already was fixed. If persist in your environment, would be good to create another issue.

**Comment by vitormattos** [comment] 2023-10-31 13:51
About PDF-signer: isn't a dockerized solution, have a docker-compose only to development environment and to make easy to help at development. This a PHP package installed by composer.

Don't worry about German, English also isn't my main language. The important is to send the message that we want as the right way and get the right understanding, if we identify that the meaning is wrong, is time to fix :-) Like about php-pdf. Sometimes the application of words won't will be the best because in my language or in your native language we have specific usages of words that isn't easy to translate to English.

Following about the subject of this issue...

Looking the error message, sounds that the problem is about configuration of your PHP. At this time the PDF file is stored at variable and will be necessary to have a `memory_limit` at your php.ini file that can store besides the memory to run Nextcloud, more allowed memory to store the PDF content. A workaround that you can do is set this to `-1` and run again your test.

PS: Today is 31'th October, the day that Martin Luther, a very important man to German culture, did a imporant step that changed the German culture. As you a German man, I send my congratulations to you about this day.

**Comment by vitormattos** [comment] 2023-11-18 14:38
Will be necessary, from development side, to generate a big PDF file and check what happening and what will be necessary to fix this problem.

All changes only will come in the next version of LibreSign and have more info here about next version:

- https://github.com/LibreSign/libresign/issues/1959

**Comment by vitormattos** [comment] 2024-04-24 15:50
Could you check again at the newest release of LibreSign?

I made a lot of improvements. To test I signed the bible with 100 signers, worked fine to me.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Closed by vitormattos** 2024-04-24 15:50 UTC
