### ISSUE TITLE
JS error "cannot read properties of null (reading 'uuid')" when open details of a file

### ISSUE THREAD

**Issue by wmeneses** [LibreSign/libresign#3145] opened 2024-06-13 16:01 UTC
when I access through the libresign icon, the other icons in the bar disappear, when I click on the PDF the sidebar does not load and it is not possible to sign.

Enviroment:

ubuntu server
Browser: any
LibreSign Versión 8.0.2
Nextcloud 28.0.6
Logs (No log error from libresign)

![libre](https://github.com/LibreSign/libresign/assets/5956910/201348c3-5490-4b62-8043-286e48883b96)

**Environment information (please complete the following information):**
 - OS: [e.g. Linux Debian, Docker]
 - LibreSign Version [e.g. 3.2.1]
 - Nextcloud Server Version [e.g. 24.0.1]
 - Logs (get the entries from nextcloud.log related with LibreSign i.e `tail -f data/nextcloud.log|grep libresign`)

**Comment by vitormattos** [comment] 2024-06-13 17:32
Thanks a lot by your report

Have two types of pages at LibreSIgn:

1. to authenticated accounts.
  This will display the menu bar
3. Public pages, to signers that haven't account (signing by email by example)
  This page don't will display the menu bar

I need to make more tests to identify the cases that a link of public page is displayed to an authenticated account.

I already identified a moment:
- https://github.com/LibreSign/libresign/issues/3133

This need to be fixed.

But could have other scenarios that reproduce the same behavior.

If possible to check what's the steps to reproduce your problem will be excellent to define a right title to this issue and to check if isn't the same scenario of issue #3133. Could you check this and return here with more details?

**Comment by wmeneses** [comment] 2024-06-13 18:17
I am not sure, that it is the same case, it happens to me that simply the sidebar does not load anymore, generating that javascript error when I select the file to sign, the signing process seems to be correct.
![imagen_2024-06-13_131724312](https://github.com/LibreSign/libresign/assets/5956910/e5089e0f-d0ae-4842-9efc-ed45ff5c4fd4)

**Comment by vitormattos** [comment] 2024-06-13 18:58
I identified the points at RequestSignatureTab.vue that use the property uid
I will review those pieces of code to verify what's happening.
For now, I will rename this issue to be about this JS error because is the point that we identified.

**Comment by wmeneses** [comment] 2024-06-13 19:10
Thank you very much, thank you guys for such a wonderful job. I hope you continue to improve it. I'll keep an eye on this error.

**Comment by wmeneses** [comment] 2024-06-17 16:07
Hi, I have performed the same test, but with local users and it works fine.

I see what happens with my LDAP users

**Comment by vitormattos** [comment] 2024-06-17 19:26
Good!

I will made a best check at the point of code that throws the error and keep in mind this information.

**Comment by wmeneses** [comment] 2024-06-17 23:54
it seems to be with certain users, I have noticed that it may be because they delete the default folder (LibreSign) that is created in nextcloud, but if I try to create the same folder it still does not work, can it be that, is there a way to "clean" some registry in the user account?

**Comment by wmeneses** [comment] 2024-06-18 13:08
Hi, I have tested this theory and indeed it is that I deleted the libresign folder of several users, because I changed the name from the configuration, I restored the folder and it worked again.

I do not know if this case can be closed, or if it is preferable that in the future this has a solution to prevent a user to do so and lose this functionality, something like "rebuild my signature folder".

Thanks!

**Comment by vitormattos** [comment] 2024-06-18 15:54
If I understood, this problem occur after then you delete the LibreSign folder of an account that already signed a document using visible signature and using a certificate, right? And after then you restored the folder, the problem was solved.

**Comment by wmeneses** [comment] 2024-06-18 16:02
> If I understood, this problem occur after then you delete the LibreSign folder of an account that already signed a document using visible signature and using a certificate, right? And after then you restored the folder, the problem was solved.

Yes, it was solved by restoring the folders.

**Comment by vitormattos** [comment] 2024-06-18 16:04
Let's maintain this open. Now we have a scenario to reproduce the problem.

I will check this.

**Comment by vitormattos** [comment] 2024-11-15 17:49
Hi @wmeneses I made a new test without success to reproduce the issue. This sounds good, but I didn't remember that I solved this, maybe was "accidentally" solved and this also is good.

Could you test again with the newest release of LibreSign and give feedback here about your tests related to this issue?

**Comment by vitormattos** [comment] 2024-11-15 19:46
Could you check again at the newest release of LibreSign?

I made a lot of improvements.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Closed by vitormattos** 2024-11-15 19:46 UTC
Labels: good first issue, frontend
