### ISSUE TITLE
Error when set the visible signature of a signer without account

### ISSUE THREAD

**Issue by alfany** [LibreSign/libresign#3660] opened 2024-09-12 05:05 UTC
**Describe the bug**
references from issue [#3543](https://github.com/LibreSign/libresign/issues/3543)
after upgrade libresign to v9.3.1 signed the document not success, got message "internal error"

**Log**
{"reqId":"wKPuFpHppm7N7y03f0Bn","level":3,"time":"2024-09-12T05:10:01+00:00","remoteAddr":"114.10.47.138","user":"--","app":"PHP","method":"POST","url":"/ocs/v2.php/apps/libresign/api/v1/signature/elements","message":"Undefined array key \"nodeId\" at /home/u444396987/domains/mydomain.com/public_html/work/apps/libresign/lib/Service/AccountService.php#412","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0","version":"29.0.5.1","data":{"app":"PHP"},"id":"66e278012be64"}

{"reqId":"CMNynWMMLnqwY9eiiHUa","level":3,"time":"2024-09-12T05:10:57+00:00","remoteAddr":"114.10.47.138","user":"--","app":"libresign","method":"POST","url":"/ocs/v2.php/apps/libresign/api/v1/sign/uuid/509f1400-bcaa-4725-93a1-d584de17a9a2","message":"OCA\\Libresign\\Service\\SignFileService::forceSaveFileOfDifferentUser(): Argument #2 ($content) must be of type string, bool given, called in /home/u444396987/domains/mydomain.com/public_html/work/apps/libresign/lib/Service/SignFileService.php on line 590","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0","version":"29.0.5.1","data":{"app":"libresign"},"id":"66e278012ad93"}

{"reqId":"CMNynWMMLnqwY9eiiHUa","level":3,"time":"2024-09-12T05:10:57+00:00","remoteAddr":"114.10.47.138","user":"--","app":"libresign","method":"POST","url":"/ocs/v2.php/apps/libresign/api/v1/sign/uuid/509f1400-bcaa-4725-93a1-d584de17a9a2","message":"[{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Service\\/SignFileService.php\",\"line\":590,\"function\":\"forceSaveFileOfDifferentUser\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Service\\/SignFileService.php\",\"line\":423,\"function\":\"getPdfToSign\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Service\\/SignFileService.php\",\"line\":282,\"function\":\"getFileToSing\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Controller\\/SignFileController.php\",\"line\":145,\"function\":\"sign\",\"class\":\"OCA\\\\Libresign\\\\Service\\\\SignFileService\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/apps\\/libresign\\/lib\\/Controller\\/SignFileController.php\",\"line\":111,\"function\":\"sign\",\"class\":\"OCA\\\\Libresign\\\\Controller\\\\SignFileController\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php\",\"line\":232,\"function\":\"signUsingUuid\",\"class\":\"OCA\\\\Libresign\\\\Controller\\\\SignFileController\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php\",\"line\":138,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/lib\\/private\\/AppFramework\\/App.php\",\"line\":184,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/lib\\/private\\/Route\\/Router.php\",\"line\":338,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/ocs\\/v1.php\",\"line\":66,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\"},{\"file\":\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/ocs\\/v2.php\",\"line\":23,\"args\":[\"\\/home\\/u444396987\\/domains\\/mydomain.com\\/public_html\\/work\\/ocs\\/v1.php\"],\"function\":\"require_once\"}]","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0","version":"29.0.5.1","data":{"app":"libresign"},"id":"66e278012ad85"}

{"reqId":"0ADEqgTuLXWhgMIogXDj","level":1,"time":"2024-09-12T05:11:10+00:00","remoteAddr":"2a02:4780:8:5::7","user":"--","app":"no app in context","method":"HEAD","url":"/data/.ocdata","message":"Unable to generate a URL for the named route \"libresign.page.index\" as such route does not exist.","userAgent":"Nextcloud Server Crawler","version":"29.0.5.1","exception":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"libresign.page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/Route/Router.php","line":410,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/Route/CachingRouter.php","line":65,"function":"generate","class":"OC\\Route\\Router","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/URLGenerator.php","line":103,"function":"generate","class":"OC\\Route\\CachingRouter","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/NavigationManager.php","line":371,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/NavigationManager.php","line":132,"function":"init","class":"OC\\NavigationManager","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/apps/theming/lib/ThemingDefaults.php","line":199,"function":"getAll","class":"OC\\NavigationManager","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/legacy/OC_Defaults.php","line":271,"function":"getShortFooter","class":"OCA\\Theming\\ThemingDefaults","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/public/Defaults.php","line":176,"function":"getLongFooter","class":"OC_Defaults","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/core/templates/layout.guest.php","line":51,"function":"getLongFooter","class":"OCP\\Defaults","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/Template/Base.php","line":180,"args":["/home/u444396987/domains/mydomain.com/public_html/work/core/templates/layout.guest.php"],"function":"include"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/legacy/OC_Template.php","line":142,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/legacy/OC_Template.php","line":173,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/public/AppFramework/Http/TemplateResponse.php","line":211,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/AppFramework/Http/Dispatcher.php","line":183,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/private/Route/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/lib/base.php","line":1101,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/home/u444396987/domains/mydomain.com/public_html/work/index.php","line":49,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/u444396987/domains/mydomain.com/public_html/work/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":144,"message":"Unable to generate a URL for the named route \"libresign.page.index\" as such route does not exist.","exception":[],"CustomMessage":"Unable to generate a URL for the named route \"libresign.page.index\" as such route does not exist."},"id":"66e278012a9c7"}

**Comment by vitormattos** [comment] 2024-09-13 02:26
I changed the description of this issue.
Could you check if is OK the description? Is this the scenario to reproduce the problem?

**Comment by vitormattos** [comment] 2024-09-13 02:28
I created a PR that I think can solve your scenario. Could you apply the change of this PR handmade and check if will solve your problem?

**Comment by alfany** [comment] 2024-09-13 05:48
Yes, the description of error/issue is correct. nc 29.0.5 libresign 9.3.1
Patching lib/Service/AccountService.php not work. Internal error still arise.

**Log Error**
[libresign] Error: OCA\Libresign\Service\SignFileService::forceSaveFileOfDifferentUser(): Argument #2 ($content) must be of type string, bool given, called in /home/u444396987/domains/mydomain.com/public_html/work/apps/libresign/lib/Service/SignFileService.php on line 590
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/97f50fef-f18b-4f39-9f1c-d5bc2c8aba5d
	from xxxx by -- at Sep 13, 2024, 12:37:48 PM

[libresign] Error: [{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Service\/SignFileService.php","line":590,"function":"forceSaveFileOfDifferentUser","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Service\/SignFileService.php","line":423,"function":"getPdfToSign","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Service\/SignFileService.php","line":282,"function":"getFileToSing","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":145,"function":"sign","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":111,"function":"sign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":232,"function":"signUsingUuid","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/Route\/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v1.php","line":66,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v2.php","line":23,"args":["\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v1.php"],"function":"require_once"}]
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/97f50fef-f18b-4f39-9f1c-d5bc2c8aba5d
	from xxxx by -- at Sep 13, 2024, 12:37:48 PM

**Comment by vitormattos** [comment] 2024-09-14 17:26
@alfany could you test again with this other PR?
- https://github.com/LibreSign/libresign/pull/3693

**Comment by alfany** [comment] 2024-09-14 18:14
> 
>     * [chore: validation setup improvement #3693](https://github.com/LibreSign/libresign/pull/3693)

Still got "Internal Error"

**Log**
[libresign] Error: OCA\Libresign\Service\SignFileService::forceSaveFileOfDifferentUser(): Argument #2 ($content) must be of type string, bool given, called in /home/u444396987/domains/mydomain.com/public_html/work/apps/libresign/lib/Service/SignFileService.php on line 577
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/aaeb03c3-9586-4ab1-93c9-450fbf264837
	from IP4xxx by -- at Sep 15, 2024, 12:57:53 AM

[libresign] Error: [{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Service\/SignFileService.php","line":577,"function":"forceSaveFileOfDifferentUser","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Service\/SignFileService.php","line":407,"function":"getPdfToSign","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Service\/SignFileService.php","line":266,"function":"getFileToSing","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":145,"function":"sign","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":111,"function":"sign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":232,"function":"signUsingUuid","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/Route\/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v1.php","line":66,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v2.php","line":23,"args":["\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v1.php"],"function":"require_once"}]
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/aaeb03c3-9586-4ab1-93c9-450fbf264837
	from IP4xxx by -- at Sep 15, 2024, 12:57:53 AM

[no app in context] Info: Unable to generate a URL for the named route "libresign.page.index" as such route does not exist.
	HEAD /data/.ocdata
	from IP6xxx by -- at Sep 15, 2024, 12:58:03 AM

**Comment by alfany** [comment] 2024-09-15 02:45
This another error log that i found:

**Log**
[libresign] Error: Error at JSignPdf side. LibreSign can not do nothing. Follow the error message: Error to sign PDF. ["#","# There is insufficient memory for the Java Runtime Environment to continue.","# Native memory allocation (mmap) failed to map 67108864 bytes for Failed to reserve memory for metaspace","# An error report file with more information is saved as:","# \/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/[hs_err_pid9148.log](https://github.com/user-attachments/files/17004435/hs_err_pid9148.log)"]
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/27dc8332-ba01-4849-bae4-b2eb89dc61de
	from IPxxx by -- at Sep 15, 2024, 9:30:05 AM

[libresign] Error: Error to sign PDF. ["#","# There is insufficient memory for the Java Runtime Environment to continue.","# Native memory allocation (mmap) failed to map 67108864 bytes for Failed to reserve memory for metaspace","# An error report file with more information is saved as:","# \/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/hs_err_pid9148.log"]
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/27dc8332-ba01-4849-bae4-b2eb89dc61de
	from IPxxx by -- at Sep 15, 2024, 9:30:05 AM

[libresign] Error: [{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Handler\/JSignPdfHandler.php","line":121,"function":"signWrapper","class":"OCA\\Libresign\\Handler\\JSignPdfHandler","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Handler\/JSignPdfHandler.php","line":92,"function":"signUsingVisibleElements","class":"OCA\\Libresign\\Handler\\JSignPdfHandler","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Handler\/Pkcs12Handler.php","line":149,"function":"sign","class":"OCA\\Libresign\\Handler\\JSignPdfHandler","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Service\/SignFileService.php","line":275,"function":"sign","class":"OCA\\Libresign\\Handler\\Pkcs12Handler","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":145,"function":"sign","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":111,"function":"sign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":232,"function":"signUsingUuid","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/Route\/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v1.php","line":66,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v2.php","line":23,"args":["\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v1.php"],"function":"require_once"}]
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/27dc8332-ba01-4849-bae4-b2eb89dc61de
	from IPxxx by -- at Sep 15, 2024, 9:30:05 AM

**Comment by vitormattos** [comment] 2024-09-15 10:58
The scenario to reproduce the steps that you made to trigger this log is important.

What's the LibreSign version that you are using?

What's the content of your Administration settings > LibreSign screen?

Sounds that you haven't enough memory. What's the return of command `free -mh` ?

Your log returned that generated the log file `work/ocs/[hs_err_pid9148.log`, whats the content of this file?

If possible, could you attach the PDF file that is triggering this error?

**Comment by alfany** [comment] 2024-09-17 05:39
Libresign v9.3.1
NC 29.0.5

the error/log trigger after non-user sign the document
![sign1](https://github.com/user-attachments/assets/21aca0de-094d-496e-89fa-5d66169544a4)

**the memory status on current test**
total        used        free      shared  buff/cache   available
Mem:           250G         54G         25G         31G        170G        162G
Swap:            0B          0B          0B

**the log produced**
[libresign] Error: Error at JSignPdf side. LibreSign can not do nothing. Follow the error message: Error to sign PDF. ["#","# There is insufficient memory for the Java Runtime Environment to continue.","# Native memory allocation (mmap) failed to map 67108864 bytes for Failed to reserve memory for metaspace","# An error report file with more information is saved as:","# \/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/hs_err_pid20283.log"]
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/25db30e5-8806-4f7e-b574-f29e4351b62b
	from 114.10.47.172 by -- at Sep 17, 2024, 12:16:31 PM

[libresign] Error: Error to sign PDF. ["#","# There is insufficient memory for the Java Runtime Environment to continue.","# Native memory allocation (mmap) failed to map 67108864 bytes for Failed to reserve memory for metaspace","# An error report file with more information is saved as:","# \/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/hs_err_pid20283.log"]
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/25db30e5-8806-4f7e-b574-f29e4351b62b
	from 114.10.47.172 by -- at Sep 17, 2024, 12:16:31 PM

[libresign] Error: [{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Handler\/JSignPdfHandler.php","line":121,"function":"signWrapper","class":"OCA\\Libresign\\Handler\\JSignPdfHandler","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Handler\/JSignPdfHandler.php","line":92,"function":"signUsingVisibleElements","class":"OCA\\Libresign\\Handler\\JSignPdfHandler","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Handler\/Pkcs12Handler.php","line":149,"function":"sign","class":"OCA\\Libresign\\Handler\\JSignPdfHandler","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Service\/SignFileService.php","line":291,"function":"sign","class":"OCA\\Libresign\\Handler\\Pkcs12Handler","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":145,"function":"sign","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/apps\/libresign\/lib\/Controller\/SignFileController.php","line":111,"function":"sign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":232,"function":"signUsingUuid","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/AppFramework\/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/lib\/private\/Route\/Router.php","line":338,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v1.php","line":66,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v2.php","line":23,"args":["\/home\/u444396987\/domains\/mydomain.com\/public_html\/work\/ocs\/v1.php"],"function":"require_once"}]
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/25db30e5-8806-4f7e-b574-f29e4351b62b
	from 114.10.47.172 by -- at Sep 17, 2024, 12:16:31 PM

**this the log of pid20283**
[hs_err_pid20283.log](https://github.com/user-attachments/files/17023267/hs_err_pid20283.log)

**configure checked and setting of libresign**
![check-confg](https://github.com/user-attachments/assets/c5c2f7cb-bf5a-4190-9e42-a83da1d6f8db)

![set1](https://github.com/user-attachments/assets/3e06f86e-5ae1-49f3-bede-1b827bc55ceb)

![set2](https://github.com/user-attachments/assets/f27386b6-d24f-4322-9c6a-aa073a23fc98)
![set3](https://github.com/user-attachments/assets/24319f77-cdf2-43c8-b2d6-55b27b0bb5cb)
![set4](https://github.com/user-attachments/assets/457b7fe8-a9d9-4d71-93c1-b99c365edb94)

**Comment by vitormattos** [comment] 2024-09-17 11:34
```
occ config:app:get libresign java_path
```

This will return the full path of java binary.

Change this setting with the follow command to make a test if will work:

```
occ config:app:set libresign java_path --value `occ config:app:get libresign java_path`" -XX:HeapBaseMinAddress=n"
```

**Comment by alfany** [comment] 2024-09-21 03:55
> ```
> occ config:app:get libresign java_path
> ```
> 
> This will return the full path of java binary.
> 
> Change this setting with the follow command to make a test if will work:
> 
> ```
> occ config:app:set libresign java_path --value `occ config:app:get libresign java_path`" -XX:HeapBaseMinAddress=n"
> ```

setting HeapBaseAddress not work and made libresign cannot find java path
**log**
[libresign] Error: Invalid Java binary. Run occ libresign:install --java
	POST /ocs/v2.php/apps/libresign/api/v1/sign/uuid/592fcd08-8142-4ae5-b1d8-b16610f9b3b0
	from 114.10.47.172 by -- at Sep 21, 2024, 10:41:35 AM

**Comment by syldri** [comment] 2024-10-23 03:42
I have the same problem. I don't understand, did you manage to find the solution?

**Comment by vitormattos** [comment] 2024-10-23 13:51
Hi @syldri I can't reproduce this issue here.
Could you provide more details or write your steps to reproduce this issue?

**Comment by yslflow** [comment] 2024-10-24 00:23
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by vitormattos** [comment] 2024-11-15 19:44
Could you check again at the newest release of LibreSign?

I made a lot of improvements that touch this flow but I can't reproduce this.

Closing this issue as solved.

If this issue persists, don't hesitate to open a new issue making reference to this.

> [!NOTE]
> ### If you like this app, don't hesitate to help us
> Ways to help this project:
> - Creating a very nice review of this project at:
>   - **social networks** like LinkedIn, Instagram, etc and putting the @LibreSign and @LibreCodeCoop
>   - **AlternativeTo** https://alternativeto.net/software/libresign/
>   - **Nextcloud apps store**: https://apps.nextcloud.com/apps/libresign
> - Sponsoring the development by **GitHub sponsor** https://github.com/sponsors/LibreSign
> - **helping the translations** on [Transifex](https://app.transifex.com/nextcloud/nextcloud/libresign/)
> - contacting us to have **Enterprise support**: https://libresign.coop

**Closed by vitormattos** 2024-11-15 19:44 UTC
